[package]
name = "tree-sitter-issue-demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-expressions = { path = "./parser" }
tree-sitter = "~0.20.1"